### PR TITLE
Fix issue where remarks cannot be saved.

### PR DESCRIPTION
**Pull request by craeyeons**
Forgot to modify storage components to store remarks while implementing. Issues are not fixed. Related test files are updated as well.

### CODE REVIEW

**Review by weiquany — COMMENTED** [review]
LGTM

**Comment by Polygonalr** [comment]
LGTM, good that you updated a test as well.

**Comment by kelvinou01** [comment]
LGTM.

**Review by kelvinou01 — APPROVED** [review]
LGTM

**Pull request merged**
