### PR TITLE
Fix tagging bugs

### LINKED ISSUE #138: [PE-D][Tester E] Unexpected behaviour for Tag parameter in Edit Command
Before Edit Command (No tag is provided)

After Edit Command (Tag is shown)

The User Guide states that at least one of the optional fields should exist. However, when I edit a contact without a tag to have a tag, the tag is added to the contact. Is this behaviour supposed to happen? If so, perhaps considering adding it to the User Guide for better clarification.

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: elizabethhky/ped#9

### PR DESCRIPTION
**Pull request by kelvinou01**
Fixes #138

### CODE REVIEW

**Review by malwaregarry — APPROVED** [review]
LGTM!

**Comment by kelvinou01** [comment]
@malwaregarry A few changes have been added to the old test cases, how do they look?

**Comment by malwaregarry** [comment]
Hi sorry, @kelvinou01 the same problem with editing a tag exists with the add command as well

**Comment by weiquany** [comment]
> Hi sorry, missed it earlier. @kelvinou01 the same problem with the edit command exists with the add command as well. Tests look great btw

Let's merge this PR first, I will apply the same fix for the add command.

**Pull request merged**
