### PR TITLE
Add feature-remark and Revise command syntaxes

### PR DESCRIPTION
**Pull request by craeyeons**
**Add feature-remark:**
We can now leave a remark for each user.

**Revise command syntaxes:**
Parameters of commands are now indicated with its own unique letter followed by a =, for example n=

### CODE REVIEW

**Review by kelvinou01 — COMMENTED** [review]
LGTM

**Review by malwaregarry — APPROVED** [review]
LGTM. I think we should merge this.

**Comment by malwaregarry** [comment]
Closes #41 and #12

**Comment by craeyeons** [comment]
Closes #34 
Closes #35 
Closes #36

**Pull request merged**
